SELECT TR.ID, TY.NAME AS TYPE, SRC.NAME AS SRC_STN, DST.NAME AS DST_STN, 
       TIMEDIFF(TR.ARRIVAL, TR.DEPARTURE) AS TRAVEL_TIME
FROM TRAINS TR
INNER JOIN TYPES TY ON TR.TYPE = TY.ID
INNER JOIN STATIONS SRC ON TR.SRC_STN = SRC.ID
INNER JOIN STATIONS DST ON TR.DST_STN = DST.ID
ORDER BY TRAVEL_TIME DESC
LIMIT 6;
