SELECT TY.NAME AS TYPE, SRC.NAME AS SRC_STN, DST.NAME AS DST_STN, 
       TR.DEPARTURE, TR.ARRIVAL, ROUND((TY.FARE_RATE * TR.DISTANCE / 1000), -2) AS FARE
FROM TRAINS TR
INNER JOIN TYPES TY ON TR.TYPE = TY.ID
INNER JOIN STATIONS SRC ON TR.SRC_STN = SRC.ID
INNER JOIN STATIONS DST ON TR.DST_STN = DST.ID
ORDER BY TR.DEPARTURE;
