SELECT TR.ID, TY.NAME AS TYPE, SRC.NAME AS SRC_STN, DST.NAME AS DST_STN, 
       COALESCE(COUNT(T.ID), 0) AS OCCUPIED, TY.MAX_SEATS AS MAXIMUM
FROM TRAINS TR
INNER JOIN TYPES TY ON TR.TYPE = TY.ID
INNER JOIN STATIONS SRC ON TR.SRC_STN = SRC.ID
INNER JOIN STATIONS DST ON TR.DST_STN = DST.ID
LEFT JOIN TICKETS T ON TR.ID = T.TRAIN_ID
GROUP BY TR.ID
ORDER BY TR.ID;
