SELECT U.ID, U.NAME, COUNT(*) AS TRAINS_COUNT, SUM(TR.DISTANCE) / 10 AS TOTAL_DISTANCE
FROM USERS U
INNER JOIN TICKETS T ON U.ID = T.USER_ID
INNER JOIN TRAINS TR ON T.TRAIN_ID = TR.ID
GROUP BY U.ID
ORDER BY TOTAL_DISTANCE DESC
LIMIT 6;
